-- Wave 1: users (tenancy root).
-- Source: docs/PHYSICAL_DATABASE_DESIGN.md § users
-- UUIDv7 values are generated by the application before INSERT.

CREATE TABLE IF NOT EXISTS users (
    id              uuid        NOT NULL,
    public_id       text        NOT NULL,
    email           text        NOT NULL,
    email_verified  boolean     NOT NULL DEFAULT false,
    display_name    text        NULL,
    avatar_url      text        NULL,
    timezone        text        NOT NULL DEFAULT 'UTC',
    locale          text        NULL,
    status          text        NOT NULL DEFAULT 'active',
    last_login_at   timestamptz NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted_at      timestamptz NULL,

    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_public_id_key UNIQUE (public_id),
    CONSTRAINT users_status_check CHECK (status IN ('active', 'disabled', 'pending_deletion')),
    CONSTRAINT users_email_not_empty_check CHECK (email <> ''),
    CONSTRAINT users_public_id_prefix_check CHECK (public_id LIKE 'usr_%'),
    CONSTRAINT users_timezone_not_empty_check CHECK (timezone <> '')
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_live_uidx
    ON users (email)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS users_status_live_idx
    ON users (status)
    WHERE deleted_at IS NULL;

COMMENT ON TABLE users IS 'Donna account / Phase 1 tenancy root.';
COMMENT ON COLUMN users.id IS 'Internal primary key (UUIDv7, application-generated).';
COMMENT ON COLUMN users.public_id IS 'Stable API identifier with usr_ prefix (application-generated, immutable).';
COMMENT ON COLUMN users.email IS 'Primary email; application lowercases before insert.';
COMMENT ON COLUMN users.email_verified IS 'Whether email was verified via identity provider.';
COMMENT ON COLUMN users.display_name IS 'Human-readable display name.';
COMMENT ON COLUMN users.avatar_url IS 'Profile image URL (not stored binary).';
COMMENT ON COLUMN users.timezone IS 'IANA timezone for local-time interpretation.';
COMMENT ON COLUMN users.locale IS 'Optional BCP 47 locale.';
COMMENT ON COLUMN users.status IS 'Lifecycle: active | disabled | pending_deletion.';
COMMENT ON COLUMN users.last_login_at IS 'Timestamp of last successful authentication.';
COMMENT ON COLUMN users.created_at IS 'Row creation time (UTC).';
COMMENT ON COLUMN users.updated_at IS 'Last mutation time; maintained by application.';
COMMENT ON COLUMN users.deleted_at IS 'Soft-delete marker; NULL means live.';
