export const timelineStyles = {
  root: "flex h-full min-h-0 flex-col",
  allDay: "border-b border-donna-hairline bg-donna-surface/60 px-3 py-2",
  allDayLabel: "mb-1.5 text-[10px] font-semibold uppercase tracking-[0.12em] text-donna-faint",
  allDayList: "flex flex-wrap gap-1.5",
  scroll: "relative min-h-0 flex-1 overflow-auto",
  grid: "relative",
  hourRow: "relative flex border-b border-donna-hairline/70",
  gutter: [
    "sticky left-0 z-10 w-14 shrink-0 border-r border-donna-hairline",
    "bg-donna-bg pr-2 pt-0 text-right text-[11px] text-donna-faint",
  ].join(" "),
  gutterLabel: "-translate-y-1/2",
  lane: "relative flex-1",
  nowLine: "pointer-events-none absolute right-0 left-14 z-20",
  nowDot: "absolute -left-[5px] top-1/2 h-2.5 w-2.5 -translate-y-1/2 rounded-full bg-rose-500",
  nowRule: "h-px w-full bg-rose-500/90",
  eventAbs: "absolute px-0.5",
  empty: "flex flex-1 items-center justify-center p-8 text-sm text-donna-muted",
  weekHeader: [
    "sticky top-0 z-20 grid border-b border-donna-hairline",
    "bg-donna-surface/90 backdrop-blur-md",
  ].join(" "),
  weekHeaderGutter: "w-14 border-r border-donna-hairline",
  weekDayHead: "border-l border-donna-hairline px-2 py-2 text-center",
  weekDayName: "text-[10px] font-semibold uppercase tracking-wider text-donna-faint",
  weekDayNum: "mt-0.5 text-sm font-medium text-donna-text",
  weekDayToday: "text-donna-accent",
  weekCols: "relative flex min-w-[640px]",
  weekCol: "relative flex-1 border-l border-donna-hairline",
  weekAllDay: "grid border-b border-donna-hairline bg-donna-surface/40",
  monthRoot: "h-full overflow-auto p-3 sm:p-4",
  monthGrid: "grid min-h-full grid-cols-7 gap-px overflow-hidden rounded-2xl border border-donna-border bg-donna-hairline",
  monthWeekday: "bg-donna-surface px-2 py-2 text-center text-[10px] font-semibold uppercase tracking-wider text-donna-faint",
  monthCell: [
    "min-h-[6.5rem] bg-donna-surface p-1.5 transition-colors sm:min-h-[7.5rem]",
    "hover:bg-donna-surface-2",
  ].join(" "),
  monthCellMuted: "bg-donna-bg/80 opacity-70",
  monthCellToday: "ring-1 ring-inset ring-donna-accent/50",
  monthDateBtn: [
    "mb-1 inline-flex h-7 w-7 items-center justify-center rounded-full text-xs",
    "text-donna-muted hover:bg-donna-accent-soft hover:text-donna-text",
  ].join(" "),
  monthDateToday: "bg-donna-accent font-semibold text-donna-on-accent hover:bg-donna-accent-bright",
  monthChips: "space-y-0.5",
  monthChip: [
    "flex w-full items-center gap-1 truncate rounded-md px-1.5 py-0.5",
    "text-left text-[10px] font-medium",
  ].join(" "),
  monthMore: "w-full px-1 text-left text-[10px] text-donna-muted hover:text-donna-text",
  agendaRoot: "h-full overflow-auto",
  agendaGroup: "border-b border-donna-hairline",
  agendaSticky: [
    "sticky top-0 z-10 border-b border-donna-hairline",
    "bg-donna-surface/95 px-4 py-2.5 backdrop-blur-md",
  ].join(" "),
  agendaDate: "text-sm font-medium text-donna-text",
  agendaList: "space-y-2 px-4 py-3",
  agendaCard: [
    "flex w-full gap-3 rounded-2xl border border-donna-border",
    "bg-donna-surface-2 p-3 text-left shadow-sm",
    "transition hover:border-donna-accent/30 hover:bg-donna-elevated",
    "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-donna-accent/40",
  ].join(" "),
  agendaColor: "mt-1 h-10 w-1 shrink-0 rounded-full",
  agendaBody: "min-w-0 flex-1",
  agendaTitle: "truncate text-sm font-medium text-donna-text",
  agendaMeta: "mt-0.5 flex flex-wrap items-center gap-2 text-xs text-donna-muted",
  skeleton: "animate-pulse space-y-3 p-4",
  skeletonBlock: "rounded-2xl bg-donna-elevated/80",
  error: "flex h-full flex-col items-center justify-center gap-3 p-8 text-center",
  errorTitle: "font-display text-xl italic text-donna-text",
  errorBody: "max-w-sm text-sm text-donna-muted",
  retry: [
    "rounded-xl border border-donna-border bg-donna-surface-2 px-4 py-2",
    "text-sm text-donna-text hover:bg-donna-accent-soft",
  ].join(" "),
} as const;
