export const settingsStyles = {
  page: "relative flex h-dvh overflow-hidden bg-donna-bg text-donna-text",
  shell: [
    "relative z-10 grid h-full w-full",
    "grid-cols-1",
    "md:grid-cols-[15rem_minmax(0,1fr)]",
  ].join(" "),
  workspace: "min-h-0 overflow-y-auto bg-donna-bg",
  workspaceInner: [
    "mx-auto flex w-full max-w-2xl flex-col gap-8 p-5 sm:p-6 lg:p-8",
  ].join(" "),
  workspaceInnerWide: [
    "mx-auto flex w-full max-w-3xl flex-col p-5 sm:p-6 lg:p-8",
  ].join(" "),
  intro: "max-w-xl",
  pageTitle: "font-display text-3xl tracking-tight text-donna-text sm:text-4xl",
  body: "mt-2 text-sm leading-relaxed text-donna-muted sm:text-[0.95rem]",
  section: "flex flex-col gap-3",
  sectionTitle: "font-display text-xl text-donna-text",
  sectionHint: "text-sm text-donna-muted",
  card: [
    "rounded-2xl border border-donna-hairline bg-donna-surface",
    "divide-y divide-donna-hairline",
  ].join(" "),
  row: "flex items-center justify-between gap-4 px-5 py-4",
  rowMain: "min-w-0",
  rowLabel: "text-sm font-medium text-donna-text",
  rowMeta: "mt-0.5 text-xs text-donna-muted",
  themeBtn: [
    "inline-flex shrink-0 items-center gap-2 rounded-full",
    "border border-donna-border bg-donna-surface-2 px-3.5 py-2",
    "text-sm text-donna-text",
    "transition-[border-color,background-color] duration-150",
    "hover:border-donna-accent/40 hover:bg-donna-accent-soft",
    "focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2",
    "focus-visible:outline-donna-accent",
  ].join(" "),
  profile: "flex items-center gap-3 px-5 py-4",
  avatar: [
    "grid h-11 w-11 shrink-0 place-items-center overflow-hidden rounded-full",
    "bg-donna-elevated text-sm font-medium text-donna-accent",
  ].join(" "),
  avatarImage: "h-full w-full object-cover",
  profileMeta: "min-w-0",
  profileName: "truncate text-sm font-semibold text-donna-text",
  profileEmail: "mt-0.5 truncate text-xs text-donna-muted",
  signOut: [
    "inline-flex shrink-0 items-center justify-center rounded-full",
    "border border-donna-border px-4 py-2 text-sm font-medium text-donna-muted",
    "transition-[border-color,color,background-color] duration-150",
    "hover:border-rose-500/40 hover:bg-rose-500/10 hover:text-rose-300",
    "focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2",
    "focus-visible:outline-donna-accent",
  ].join(" "),
} as const;
