export const integrationsStyles = {
  page: "flex flex-col gap-8",
  intro: "max-w-2xl",
  pageTitle: "font-display text-3xl tracking-tight text-donna-text sm:text-4xl",
  body: "mt-2 text-sm leading-relaxed text-donna-muted sm:text-[0.95rem]",
  section: "flex flex-col gap-4",
  sectionHead: "flex flex-wrap items-end justify-between gap-3",
  sectionTitle: "font-display text-xl text-donna-text",
  sectionHint: "text-sm text-donna-muted",
  connect: [
    "inline-flex h-10 items-center justify-center gap-2 rounded-full",
    "border border-donna-border bg-donna-surface px-5",
    "text-sm font-semibold text-donna-text",
    "transition-[border-color,color,transform] duration-200",
    "hover:-translate-y-0.5 hover:border-donna-accent/40 hover:text-donna-accent",
    "focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2",
    "focus-visible:outline-donna-accent",
  ].join(" "),
  list: "grid grid-cols-1 gap-3 sm:grid-cols-2",
  empty: [
    "rounded-2xl border border-dashed border-donna-border",
    "bg-donna-surface/40 px-5 py-6 text-sm text-donna-muted",
  ].join(" "),
  row: [
    "flex h-full flex-col gap-3 rounded-2xl border border-donna-hairline",
    "bg-donna-surface px-5 py-4",
  ].join(" "),
  rowMain: "flex min-w-0 items-start gap-3",
  avatar: [
    "grid h-10 w-10 shrink-0 place-items-center overflow-hidden rounded-full",
    "bg-donna-elevated text-xs font-semibold text-donna-accent",
  ].join(" "),
  avatarImage: "h-full w-full object-cover",
  rowMeta: "min-w-0 flex-1",
  accountName: "truncate text-sm font-semibold text-donna-text",
  accountEmail: "mt-0.5 truncate text-xs text-donna-muted",
  meta: "mt-1.5 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-donna-muted",
  badge: [
    "inline-flex items-center rounded-full",
    "bg-donna-accent/10 px-2.5 py-0.5 text-[0.7rem] font-semibold",
    "tracking-wide text-donna-accent",
  ].join(" "),
  disconnect: [
    "inline-flex h-9 w-full shrink-0 items-center justify-center rounded-full",
    "border border-donna-border px-4 text-sm font-medium text-donna-muted",
    "transition-colors hover:border-red-500/40 hover:text-red-600",
    "disabled:pointer-events-none disabled:opacity-50",
    "dark:hover:text-red-400",
  ].join(" "),
  error: "rounded-2xl border border-red-500/30 bg-red-500/5 px-4 py-3 text-sm",
  errorTitle: "font-semibold text-donna-text",
  errorBody: "mt-1 text-donna-muted",
  retry: "mt-3 text-sm font-semibold text-donna-accent hover:underline",
  skeleton: "h-24 animate-pulse rounded-2xl bg-donna-hairline",
  form: "flex flex-col gap-3 rounded-2xl border border-donna-hairline bg-donna-surface px-5 py-4",
  formFields: "grid grid-cols-1 gap-3 sm:grid-cols-[minmax(0,0.9fr)_minmax(0,1.4fr)]",
  formRow: "flex min-w-0 flex-col gap-1.5",
  label: "text-xs font-semibold tracking-wide text-donna-muted",
  input: [
    "h-10 w-full rounded-xl border border-donna-border bg-donna-elevated/40",
    "px-3 text-sm text-donna-text placeholder:text-donna-muted/70",
    "focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2",
    "focus-visible:outline-donna-accent",
  ].join(" "),
  checkboxRow: "flex items-center gap-2 text-sm text-donna-text",
  formActions: "flex flex-wrap items-center gap-3",
  formError: "text-sm text-red-600 dark:text-red-400",
  titleWithHelp: "inline-flex items-center gap-2",
  help: [
    "inline-flex h-5 w-5 items-center justify-center rounded-full",
    "border border-donna-border text-[0.65rem] font-semibold text-donna-muted",
    "hover:border-donna-accent/40 hover:text-donna-accent",
    "focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2",
    "focus-visible:outline-donna-accent",
  ].join(" "),
  rowActions: "mt-auto flex flex-wrap items-center gap-2",
  secondaryAction: [
    "inline-flex h-9 shrink-0 items-center justify-center rounded-full",
    "border border-donna-border px-4 text-sm font-medium text-donna-text",
    "transition-colors hover:border-donna-accent/40 hover:text-donna-accent",
    "disabled:pointer-events-none disabled:opacity-50",
  ].join(" "),
} as const;
