export const sidebarPanelStyles = {
  section: "space-y-3",
  sectionTitle: "text-[11px] font-semibold uppercase tracking-[0.14em] text-donna-faint",
  sourceList: "space-y-1.5",
  sourceRow: [
    "flex w-full items-center gap-2.5 rounded-xl px-2 py-2 text-left",
    "transition-colors hover:bg-donna-accent-soft",
  ].join(" "),
  checkbox: [
    "grid h-4 w-4 shrink-0 place-items-center rounded border",
    "border-donna-border bg-donna-surface-2",
  ].join(" "),
  checkboxOn: "border-donna-accent bg-donna-accent text-donna-on-accent",
  colorDot: "h-2.5 w-2.5 shrink-0 rounded-full",
  sourceName: "min-w-0 flex-1 truncate text-sm text-donna-text",
  connectHint: "text-xs leading-relaxed text-donna-muted",
  connectLink: "font-semibold text-donna-accent hover:underline",
  syncCard: "space-y-3 rounded-2xl border border-donna-border bg-donna-surface-2 p-3",
  syncMeta: "space-y-1",
  syncLabel: "text-xs text-donna-muted",
  badge: "inline-flex items-center rounded-full px-2 py-0.5 text-[11px] font-medium",
  badgeIdle: "bg-donna-elevated text-donna-muted",
  badgeOk: "bg-emerald-500/15 text-emerald-400",
  badgeWarn: "bg-amber-500/15 text-amber-400",
  badgeErr: "bg-rose-500/15 text-rose-400",
  badgeBusy: "bg-donna-accent-soft text-donna-accent",
  refreshBtn: [
    "flex w-full items-center justify-center gap-2 rounded-xl",
    "bg-donna-accent px-3 py-2.5 text-sm font-medium text-donna-on-accent",
    "transition hover:bg-donna-accent-bright disabled:opacity-60",
  ].join(" "),
  spin: "animate-spin",
} as const;
