export const toolbarStyles = {
  root: [
    "flex flex-col gap-2 border-b border-donna-hairline",
    "bg-donna-surface/80 px-3 py-2.5 backdrop-blur-md",
    "sm:flex-row sm:items-center sm:gap-3 sm:px-5",
  ].join(" "),
  topRow: "flex min-w-0 items-center gap-2 sm:flex-1",
  bottomRow: "flex min-w-0 items-center gap-1.5 sm:shrink-0 sm:gap-2",
  navGroup: "hidden shrink-0 items-center gap-0.5 sm:flex",
  mobileNav: "flex shrink-0 items-center sm:hidden",
  iconBtn: [
    "grid h-9 w-9 place-items-center rounded-lg",
    "text-donna-muted transition-colors",
    "hover:bg-donna-accent-soft hover:text-donna-text",
    "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-donna-accent/40",
  ].join(" "),
  todayBtn: [
    "hidden h-8 rounded-lg border border-donna-border bg-donna-surface-2 px-2.5",
    "text-sm font-medium text-donna-text transition-colors sm:inline-flex sm:items-center",
    "hover:bg-donna-accent-soft",
    "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-donna-accent/40",
  ].join(" "),
  dateBtn: [
    "min-w-0 flex-1 rounded-lg text-left",
    "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-donna-accent/40",
  ].join(" "),
  mobileDate: "flex min-w-0 items-baseline gap-2 sm:hidden",
  dayNumber: [
    "font-display text-[1.75rem] font-semibold leading-none tracking-tight",
    "text-donna-text",
  ].join(" "),
  dayNumberToday: "text-donna-accent",
  dayMeta: "truncate text-sm text-donna-muted",
  desktopTitle: [
    "hidden min-w-0 truncate font-display text-xl italic leading-none",
    "text-donna-text sm:block",
  ].join(" "),
  controls: [
    "flex min-w-0 flex-1 items-center rounded-xl border border-donna-border",
    "bg-donna-surface-2 p-0.5 sm:flex-none",
  ].join(" "),
  viewSwitch: [
    "flex min-w-0 flex-1 items-center",
    "sm:flex-none sm:overflow-visible",
  ].join(" "),
  viewBtn: [
    "min-w-0 flex-1 rounded-lg px-1.5 py-1.5 text-center text-xs font-medium text-donna-muted",
    "transition-colors sm:flex-none sm:px-2.5 sm:text-[13px]",
    "hover:text-donna-text",
    "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-donna-accent/40",
  ].join(" "),
  viewBtnActive: "bg-donna-elevated text-donna-text shadow-sm",
  divider: "mx-0.5 h-4 w-px shrink-0 bg-donna-border",
  syncBtn: [
    "grid h-9 w-9 shrink-0 place-items-center rounded-lg",
    "text-donna-muted transition-colors",
    "hover:bg-donna-accent-soft hover:text-donna-text",
    "disabled:opacity-50",
    "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-donna-accent/40",
    "sm:h-8 sm:w-8",
  ].join(" "),
  syncBtnActive: "text-donna-accent",
  calendarsBtn: [
    "grid h-9 w-9 shrink-0 place-items-center rounded-lg border border-donna-border",
    "text-donna-muted lg:hidden",
    "hover:bg-donna-accent-soft hover:text-donna-text",
    "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-donna-accent/40",
  ].join(" "),
  spin: "animate-spin",
} as const;
