export const automationsStyles = {
  list: "divide-y divide-donna-hairline",
  card: "flex flex-col gap-3 px-5 py-4",
  cardTop: "flex flex-col gap-1 sm:flex-row sm:items-start sm:justify-between",
  title: "text-sm font-medium text-donna-text",
  description: "text-xs text-donna-muted",
  metaGrid: "grid gap-2 sm:grid-cols-2",
  metaItem: "text-xs text-donna-muted",
  metaLabel: "font-medium text-donna-text/80",
  actions: "flex flex-wrap items-center gap-2",
  toggle: [
    "inline-flex items-center gap-2 rounded-full border border-donna-border",
    "bg-donna-surface-2 px-3 py-1.5 text-xs text-donna-text",
    "transition-[border-color,background-color] duration-150",
    "hover:border-donna-accent/40 hover:bg-donna-accent-soft",
    "focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2",
    "focus-visible:outline-donna-accent",
  ].join(" "),
  dangerBtn: [
    "inline-flex items-center justify-center rounded-full",
    "border border-donna-border px-3 py-1.5 text-xs font-medium text-donna-muted",
    "transition-[border-color,color,background-color] duration-150",
    "hover:border-rose-500/40 hover:bg-rose-500/10 hover:text-rose-300",
    "focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2",
    "focus-visible:outline-donna-accent",
  ].join(" "),
  secondaryBtn: [
    "inline-flex items-center justify-center rounded-full",
    "border border-donna-border bg-donna-surface-2 px-3 py-1.5 text-xs text-donna-text",
    "transition-[border-color,background-color] duration-150",
    "hover:border-donna-accent/40 hover:bg-donna-accent-soft",
    "focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2",
    "focus-visible:outline-donna-accent",
    "disabled:cursor-not-allowed disabled:opacity-50",
  ].join(" "),
  form: "flex flex-col gap-3 px-5 py-4",
  formRow: "grid gap-3 sm:grid-cols-[1fr_auto_auto] sm:items-end",
  field: "flex min-w-0 flex-col gap-1.5",
  label: "text-xs font-medium text-donna-muted",
  select: [
    "rounded-xl border border-donna-border bg-donna-surface-2 px-3 py-2",
    "text-sm text-donna-text",
    "focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2",
    "focus-visible:outline-donna-accent",
  ].join(" "),
  timeInput: [
    "rounded-xl border border-donna-border bg-donna-surface-2 px-3 py-2",
    "text-sm text-donna-text",
    "focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2",
    "focus-visible:outline-donna-accent",
  ].join(" "),
  textInput: [
    "rounded-xl border border-donna-border bg-donna-surface-2 px-3 py-2",
    "text-sm text-donna-text",
    "focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2",
    "focus-visible:outline-donna-accent",
  ].join(" "),
  addBtn: [
    "inline-flex shrink-0 items-center justify-center rounded-full",
    "border border-donna-border bg-donna-surface-2 px-3.5 py-2",
    "text-sm text-donna-text",
    "transition-[border-color,background-color] duration-150",
    "hover:border-donna-accent/40 hover:bg-donna-accent-soft",
    "focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2",
    "focus-visible:outline-donna-accent",
    "disabled:cursor-not-allowed disabled:opacity-50",
  ].join(" "),
  empty: "px-5 py-4 text-sm text-donna-muted",
  error: "px-5 pb-4 text-sm text-rose-300",
  note: "px-5 pb-4 text-xs text-donna-muted",
  commandsHint: "px-5 pb-2 text-xs text-donna-muted",
  notice: "mx-5 mb-4 rounded-2xl border border-donna-border bg-donna-surface-2 p-4",
  noticeTitle: "text-sm font-medium text-donna-text",
  noticeBody:
    "mt-2 whitespace-pre-wrap rounded-xl bg-donna-surface px-3 py-2 text-sm text-donna-text",
  modalBackdrop: [
    "fixed inset-0 z-50 flex items-end justify-center bg-black/50 p-4",
    "sm:items-center",
  ].join(" "),
  modal: [
    "max-h-[85vh] w-full max-w-lg overflow-y-auto rounded-2xl",
    "border border-donna-border bg-donna-surface p-5 shadow-xl",
  ].join(" "),
  modalHeader: "flex items-start justify-between gap-3",
  modalEyebrow: "text-xs uppercase tracking-[0.14em] text-donna-muted",
  modalTitle: "text-base font-medium text-donna-text",
  modalMeta: "mt-2 text-xs text-donna-muted",
  modalResponse: [
    "mt-4 whitespace-pre-wrap rounded-xl border border-donna-border",
    "bg-donna-surface-2 px-3 py-3 text-sm text-donna-text",
  ].join(" "),
  commandList: "mt-4 divide-y divide-donna-hairline border-t border-donna-hairline",
  commandRow: "py-3",
  commandName: "text-sm text-donna-text",
  commandMeta: "mt-1 text-xs text-donna-muted",
} as const;
