export const journalStyles = {
  page: "relative flex h-dvh overflow-hidden bg-donna-bg text-donna-text",
  shell: [
    "relative z-10 grid h-full w-full",
    "grid-cols-1",
    "md:grid-cols-[15rem_minmax(0,1fr)]",
  ].join(" "),
  workspace: "min-h-0 overflow-y-auto bg-donna-bg",
  workspaceInner: [
    "mx-auto grid w-full max-w-6xl gap-6 p-5 sm:p-6 lg:p-8",
    "lg:grid-cols-[minmax(0,1fr)_16rem]",
  ].join(" "),
  main: "flex min-w-0 flex-col gap-6",
  header: "flex flex-wrap items-center justify-between gap-3",
  title: "font-display text-3xl tracking-tight text-donna-text sm:text-4xl",
  nav: "flex items-center gap-2",
  navBtn: [
    "inline-flex h-9 items-center justify-center rounded-full border border-donna-border",
    "px-3.5 text-sm text-donna-muted transition-colors",
    "hover:border-donna-accent/40 hover:text-donna-text",
  ].join(" "),
  todayBtn: [
    "inline-flex h-9 items-center justify-center rounded-full",
    "border border-donna-accent/40 bg-donna-accent-soft px-3.5",
    "text-sm font-medium text-donna-accent",
  ].join(" "),
  layout: "grid gap-6 lg:grid-cols-[14rem_minmax(0,1fr)]",
  miniRoot: "rounded-2xl border border-donna-border bg-donna-surface-2 p-3",
  miniHeader: "mb-2 flex items-center justify-between",
  miniMonth: "text-sm font-medium text-donna-text",
  miniNav: "flex gap-1",
  miniNavBtn: "grid h-7 w-7 place-items-center rounded-lg text-donna-muted hover:bg-donna-accent-soft",
  miniWeekdays: "mb-1 grid grid-cols-7 gap-0.5 text-center text-[10px] text-donna-faint",
  miniGrid: "grid grid-cols-7 gap-0.5",
  miniDay: [
    "flex flex-col items-center rounded-lg px-0.5 py-1 text-[10px]",
    "text-donna-muted transition-colors hover:bg-donna-accent-soft",
  ].join(" "),
  miniDayMuted: "text-donna-faint/70",
  miniDaySelected: "bg-donna-accent text-donna-on-accent hover:bg-donna-accent",
  miniDayToday: "ring-1 ring-inset ring-donna-accent/50",
  miniCounts: "mt-0.5 text-[9px] leading-none opacity-80",
  tasksCard: "rounded-2xl border border-donna-hairline bg-donna-surface p-4 sm:p-5",
  addRow: "mb-4 flex gap-2",
  addInput: [
    "h-10 min-w-0 flex-1 rounded-xl border border-donna-border bg-donna-elevated/40",
    "px-3 text-sm text-donna-text placeholder:text-donna-muted/70",
    "focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2",
    "focus-visible:outline-donna-accent",
  ].join(" "),
  addBtn: [
    "inline-flex h-10 shrink-0 items-center justify-center rounded-xl",
    "bg-donna-accent px-4 text-sm font-medium text-donna-on-accent",
    "hover:bg-donna-accent-bright disabled:opacity-60",
  ].join(" "),
  list: "space-y-1",
  item: [
    "flex items-start gap-3 rounded-xl border border-transparent px-2 py-2.5",
    "transition-[background-color,border-color,opacity,box-shadow] duration-150",
    "hover:border-donna-hairline hover:bg-donna-surface-2/60",
  ].join(" "),
  itemDragging: "opacity-40",
  itemDropTarget: [
    "border-donna-accent/50 bg-donna-accent-soft/60",
    "shadow-[inset_0_0_0_1px_rgba(212,175,122,0.35)]",
  ].join(" "),
  checkbox: [
    "mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded border",
    "border-donna-border bg-donna-surface-2 cursor-pointer",
  ].join(" "),
  checkboxOn: "border-donna-accent bg-donna-accent text-donna-on-accent",
  itemBody: "min-w-0 flex-1",
  itemTitle: "inline text-sm text-donna-text",
  itemTitleDone: "text-donna-muted line-through",
  carriedPill: [
    "ml-2 inline-flex translate-y-[-1px] items-center rounded-full",
    "border border-donna-border bg-donna-surface-2 px-2 py-0.5",
    "align-middle text-[10px] font-medium tracking-wide text-donna-muted",
    "no-underline",
  ].join(" "),
  itemMeta: "mt-0.5 flex items-center gap-2 text-xs text-donna-faint",
  deleteBtn: [
    "mt-0.5 grid h-7 w-7 shrink-0 place-items-center rounded-lg",
    "text-donna-faint transition-colors",
    "hover:bg-donna-accent-soft hover:text-donna-text",
    "disabled:opacity-50",
  ].join(" "),
  dragHandle: [
    "mt-0.5 grid h-7 w-7 shrink-0 cursor-grab place-items-center rounded-lg",
    "text-donna-faint transition-colors active:cursor-grabbing",
    "hover:bg-donna-accent-soft hover:text-donna-text",
  ].join(" "),
  empty: "py-8 text-center text-sm text-donna-muted",
  statsCard: "rounded-2xl border border-donna-hairline bg-donna-surface p-4",
  statsTitle: "mb-3 text-[11px] font-semibold uppercase tracking-[0.14em] text-donna-faint",
  statsGrid: "space-y-3",
  statRow: "flex items-center justify-between gap-3 text-sm",
  statLabel: "text-donna-muted",
  statValue: "font-medium text-donna-text",
  state: "text-sm text-donna-muted",
} as const;
